2022-02-25 12:32:27,671 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-02-25 12:32:27,672 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\MTZ\PycharmProjects\montador de perfil\venv\lib\site-packages\instabot\bot\bot.py
2022-02-25 12:32:27,673 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-02-25 12:32:27,945 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-02-25 12:32:28,179 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-02-25 12:32:28,393 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-02-25 12:32:28,602 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-02-25 12:32:31,930 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-02-25 12:32:31,930 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXHFM3FuRuogdLrSHbzIAn7IfWjeRptuM2byZne6CGP8YVo-pR5jwx8wsSSVoQMHw0DBuTk/Z6YwRvcjXn/","api_path":"/challenge/AXHFM3FuRuogdLrSHbzIAn7IfWjeRptuM2byZne6CGP8YVo-pR5jwx8wsSSVoQMHw0DBuTk/Z6YwRvcjXn/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-02-25 12:32:31,930 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-02-25 12:32:31,931 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-02-25 12:32:31,932 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2022-02-25 12:32:34,853 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-02-25 12:32:34,854 - instabot version: 0.117.0 (bot_photo) - INFO - Photo '1.jpg' is not uploaded.
