2022-02-25 12:37:57,138 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-02-25 12:37:57,138 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\MTZ\PycharmProjects\montador de perfil\venv\lib\site-packages\instabot\bot\bot.py
2022-02-25 12:37:57,139 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-02-25 12:37:57,408 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-02-25 12:37:57,645 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-02-25 12:37:57,847 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-02-25 12:37:58,049 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-02-25 12:38:01,692 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-02-25 12:38:01,692 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXGtCj0lacfhjG6JL9cTMNi-Hyml9Hy-9lsXmxEzbzIgwOPDR9BFTdhSVtgghUd4BimfmFI/BZgSeacdVJ/","api_path":"/challenge/AXGtCj0lacfhjG6JL9cTMNi-Hyml9Hy-9lsXmxEzbzIgwOPDR9BFTdhSVtgghUd4BimfmFI/BZgSeacdVJ/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-02-25 12:38:01,692 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-02-25 12:38:01,693 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-02-25 12:38:01,693 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2022-02-25 12:38:03,587 - instabot version: 0.117.0 (api_photo) - ERROR - Photo Upload failed with the following response: <Response [403]>
2022-02-25 12:38:03,587 - instabot version: 0.117.0 (bot_photo) - INFO - Photo '1.jpg' is not uploaded.
